In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("./data/mexico2010.csv")
print(df.shape)
df.head()

(2331, 263)

,Unnamed: 0,GEO2_MX,sum_income,sum_earned_income,total_pop,MX2015A_INCOME,weighted_avg_income,weighted_avg_earned_income,perc_households_gq,unrel_ppl,...,perc_imss_public_insurance_hlthcov,perc_imss_other_hlthcov,perc_issste_pemex_military_naval_hlthcov,perc_issste_public_insurance_hlthcov,perc_issste_other_hlthcov,perc_pemex_military_naval_public_insurance_hlthcov,perc_pemex_military_naval_other_hlthcov,perc_public_insurance_other_hlthcov,perc_no_coverage_hlthcov,perc_unknown_hlthcov
0,0,484001001,22382867663,74890812.0,849101.0,2.154187e+10,629235.014487,2422.132478,1.0,0.018720,...,0.004540,0.006762,0.000026,0.000682,0.003359,0.000028,NaN,0.000324,0.184459,0.001800
1,1,484001002,3998425640,4429714.0,45951.0,3.918426e+09,741268.336902,806.425562,1.0,0.006768,...,0.011491,NaN,NaN,0.000348,NaN,NaN,NaN,0.000196,0.118909,0.001763
2,2,484001003,3045860068,4863177.0,53142.0,2.977860e+09,667268.590569,1054.225039,1.0,0.011385,...,0.002936,0.000207,NaN,0.000884,0.000207,NaN,NaN,NaN,0.163280,0.001694
3,3,484001004,3449277596,4281138.0,14302.0,3.352278e+09,718626.207244,965.081247,1.0,0.000839,...,0.035659,NaN,NaN,0.000559,NaN,NaN,NaN,NaN,0.101454,0.014683
4,4,484001005,3028539049,8542158.0,100150.0,2.939539e+09,662572.130694,1823.933390,1.0,0.019251,...,0.006390,0.003844,NaN,0.000200,NaN,NaN,NaN,0.001398,0.119830,0.003245

In [5]:
c = pd.read_csv("./data/mex_crime_subevent.csv")
print(c.shape)
c.head()

(1547, 20)

,GEOLEVEL2,abduction_forced_disappearance,agreement,air_drone_strike,armed_clash,arrests,attack,change_to_group_activity,disrupted_weapons_use,excessive_force_against_protesters,grenade,headquarters_or_base_established,looting_property_destruction,mob_violence,other,peaceful_protest,protest_with_intervention,remote_explosive_landmine_ied,sexual_violence,violent_demonstration
0,484001001,1.0,0.0,0.0,9.0,4.0,11.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0,0.0,46.0,2.0,0.0,0.0,3.0
1,484001002,1.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,484001004,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,484001006,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,484002001,1.0,0.0,0.0,40.0,0.0,129.0,0.0,0.0,0.0,0.0,0.0,34.0,2.0,0.0,59.0,1.0,0.0,0.0,5.0

In [11]:
pd.merge(df, c, left_on = "GEO2_MX", right_on = "GEOLEVEL2", how = "left").fillna(0).to_csv("./data/mexico2010_wcrime.csv")